"""Added notification mode column in Guilds table

Revision ID: ea6425e582ab
Revises: c2464106098a
Create Date: 2024-03-08 07:01:10.129810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea6425e582ab'
down_revision: Union[str, None] = 'c2464106098a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guilds', sa.Column('notification_mode', sa.String(), nullable=False, server_default='optin'))
    op.alter_column('streamers', 'streamer_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('streamers', 'topic_sub_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('streamers', 'topic_sub_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('streamers', 'streamer_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('guilds', 'notification_mode')
    # ### end Alembic commands ###
